/* Generated by Yosys 0.68+195 (git sha1 435977e97, GNU /usr/bin/c++ 11.4.0) */

(* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:1.1-21.10" *)
module alu(a, b, alu_ctrl, result, zero);
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:2.18-2.19" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:3.18-3.19" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:4.17-4.25" *)
  input [2:0] alu_ctrl;
  wire [2:0] alu_ctrl;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:5.23-5.29" *)
  output [15:0] result;
  wire [15:0] result;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:6.12-6.16" *)
  output zero;
  wire zero;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:8.5-19.8" *)
  wire [15:0] _00_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:8.5-19.8" *)
  wire [15:0] _01_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:10.30-10.35" *)
  wire [15:0] _02_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:12.30-12.35" *)
  wire [15:0] _03_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:20.20-20.35" *)
  wire _04_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:13.30-13.35" *)
  wire [15:0] _05_;
  wire [15:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:15.30-15.36" *)
  wire [15:0] _14_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:16.30-16.36" *)
  wire [15:0] _15_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:11.30-11.35" *)
  wire [15:0] _16_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:14.30-14.35" *)
  wire [15:0] _17_;
  assign _02_ = a + (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:10.30-10.35" *) b;
  assign _03_ = a & (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:12.30-12.35" *) b;
  assign _04_ = ! (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:20.20-20.35" *) result;
  assign _05_ = a | (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:13.30-13.35" *) b;
  function [15:0] _22_;
    input [15:0] a;
    input [111:0] b;
    input [6:0] s;
    (* full_case = 32'd1 *)
    (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:15.37-15.37|/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:9.9-18.16" *)
    (* parallel_case *)
    casez (s)
      7'b??????1:
        _22_ = b[15:0];
      7'b?????1?:
        _22_ = b[31:16];
      7'b????1??:
        _22_ = b[47:32];
      7'b???1???:
        _22_ = b[63:48];
      7'b??1????:
        _22_ = b[79:64];
      7'b?1?????:
        _22_ = b[95:80];
      7'b1??????:
        _22_ = b[111:96];
      default:
        _22_ = a;
    endcase
  endfunction
  assign _06_ = _22_(16'h0000, { _02_, _16_, _03_, _05_, _17_, _14_, _15_ }, { _13_, _12_, _11_, _10_, _09_, _08_, _07_ });
  assign _07_ = alu_ctrl == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:15.37-15.37|/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:9.9-18.16" *) 3'h6;
  assign _08_ = alu_ctrl == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:14.36-14.36|/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:9.9-18.16" *) 3'h5;
  assign _09_ = alu_ctrl == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:13.36-13.36|/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:9.9-18.16" *) 3'h4;
  assign _10_ = alu_ctrl == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:12.36-12.36|/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:9.9-18.16" *) 3'h3;
  assign _11_ = alu_ctrl == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:11.36-11.36|/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:9.9-18.16" *) 3'h2;
  assign _12_ = alu_ctrl == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:10.36-10.36|/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:9.9-18.16" *) 3'h1;
  assign _13_ = ! (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:9.24-9.24|/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:9.9-18.16" *) alu_ctrl;
  assign _16_ = a - (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:11.30-11.35" *) b;
  assign _17_ = a ^ (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/alu.v:14.30-14.35" *) b;
  assign zero = _04_;
  assign _00_ = _01_;
  assign _01_ = _06_;
  assign result = _06_;
  assign _14_ = { a[14:0], 1'h0 };
  assign _15_ = { 1'h0, a[15:1] };
endmodule

(* top =  1  *)
(* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:1.1-114.10" *)
module processor_16b(clk, reset, pc, instr, mem_addr, mem_wdata, mem_rdata, mem_we, mem_re);
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:6.23-6.25" *)
  output [15:0] pc;
  reg [15:0] pc;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:7.18-7.23" *)
  input [15:0] instr;
  wire [15:0] instr;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:10.19-10.27" *)
  output [15:0] mem_addr;
  wire [15:0] mem_addr;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:11.19-11.28" *)
  output [15:0] mem_wdata;
  wire [15:0] mem_wdata;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:12.18-12.27" *)
  input [15:0] mem_rdata;
  wire [15:0] mem_rdata;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:13.12-13.18" *)
  output mem_we;
  wire mem_we;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:14.12-14.18" *)
  output mem_re;
  wire mem_re;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:37.5-68.8" *)
  wire [2:0] _00_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:37.5-68.8" *)
  wire _01_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:37.5-68.8" *)
  wire _02_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:37.5-68.8" *)
  wire _03_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:106.5-112.8" *)
  wire [15:0] _04_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:37.5-68.8" *)
  wire _05_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:80.5-86.8" *)
  wire [15:0] _06_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:37.5-68.8" *)
  wire [2:0] _07_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:37.5-68.8" *)
  wire _08_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:37.5-68.8" *)
  wire _09_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:37.5-68.8" *)
  wire _10_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:37.5-68.8" *)
  wire _11_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:80.5-86.8" *)
  wire [15:0] _12_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:110.19-110.25" *)
  wire [31:0] _13_;
  wire _14_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:21.27-21.44" *)
  wire _15_;
  wire [15:0] _16_;
  wire _17_;
  wire [2:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:21.26-21.72" *)
  wire [3:0] _37_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:70.28-70.56" *)
  wire [15:0] _38_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:70.17-70.25" *)
  wire [15:0] alu_b_in;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:30.15-30.23" *)
  wire [2:0] alu_ctrl;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:26.17-26.27" *)
  wire [15:0] alu_result;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:33.9-33.20" *)
  wire alu_src_imm;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:27.10-27.18" *)
  wire alu_zero;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:22.17-22.20" *)
  wire [15:0] imm;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:32.9-32.17" *)
  wire mem_read;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:31.9-31.18" *)
  wire mem_write;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:17.16-17.22" *)
  wire [3:0] opcode;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:24.17-24.25" *)
  wire [15:0] rd_data1;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:25.17-25.25" *)
  wire [15:0] rd_data2;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:18.16-18.22" *)
  wire [3:0] rd_sel;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:29.9-29.15" *)
  wire reg_we;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:19.16-19.23" *)
  wire [3:0] rs1_sel;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:21.16-21.23" *)
  wire [3:0] rs2_sel;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:34.16-34.23" *)
  wire [15:0] wr_data;
  assign _13_ = pc + (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:110.19-110.25" *) 32'd2;
  assign _15_ = opcode == (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:21.27-21.44" *) 4'h9;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:106.5-112.8" *)
  always @(posedge clk, posedge _14_)
    if (_14_) pc <= 16'h0000;
    else pc <= _13_[15:0];
  assign _16_ = _17_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:81.13-81.21|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:81.9-85.12" *) mem_rdata : alu_result;
  function [2:0] _43_;
    input [2:0] a;
    input [8:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:53.16-53.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _43_ = b[2:0];
      3'b?1?:
        _43_ = b[5:3];
      3'b1??:
        _43_ = b[8:6];
      default:
        _43_ = a;
    endcase
  endfunction
  assign _18_ = _43_(3'h0, 9'h053, { _21_, _20_, _19_ });
  assign _19_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:53.16-53.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h3;
  assign _20_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:50.16-50.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h2;
  assign _21_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:47.16-47.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h1;
  function [0:0] _47_;
    input [0:0] a;
    input [5:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:59.16-59.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _47_ = b[0:0];
      6'b????1?:
        _47_ = b[1:1];
      6'b???1??:
        _47_ = b[2:2];
      6'b??1???:
        _47_ = b[3:3];
      6'b?1????:
        _47_ = b[4:4];
      6'b1?????:
        _47_ = b[5:5];
      default:
        _47_ = a;
    endcase
  endfunction
  assign _22_ = _47_(1'h0, 6'h3f, { _28_, _27_, _26_, _25_, _24_, _23_ });
  assign _23_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:59.16-59.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h8;
  assign _24_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:56.16-56.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h4;
  assign _25_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:53.16-53.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h3;
  assign _26_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:50.16-50.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h2;
  assign _27_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:47.16-47.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h1;
  assign _28_ = ! (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.22-44.22|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) opcode;
  function [0:0] _54_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:62.16-62.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _54_ = b[0:0];
      3'b?1?:
        _54_ = b[1:1];
      3'b1??:
        _54_ = b[2:2];
      default:
        _54_ = a;
    endcase
  endfunction
  assign _29_ = _54_(1'h0, 3'h7, { _32_, _31_, _30_ });
  assign _30_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:62.16-62.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h9;
  assign _31_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:59.16-59.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h8;
  assign _32_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:56.16-56.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h4;
  assign _33_ = _34_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:59.16-59.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 1'h1 : 1'h0;
  assign _34_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:59.16-59.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h8;
  assign _35_ = _36_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:62.16-62.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 1'h1 : 1'h0;
  assign _36_ = opcode == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:62.16-62.16|/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:44.9-67.16" *) 4'h9;
  assign _37_ = _15_ ? (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:21.26-21.72" *) instr[11:8] : instr[3:0];
  assign _38_ = alu_src_imm ? (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:70.28-70.56" *) imm : rd_data2;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:72.9-78.6" *)
  alu alu_inst (
    .a(rd_data1),
    .alu_ctrl(alu_ctrl),
    .b(alu_b_in),
    .result(alu_result),
    .zero(alu_zero)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/processor_16b.v:88.13-98.6" *)
  regfile regfile_inst (
    .clk(clk),
    .read_data1(rd_data1),
    .read_data2(rd_data2),
    .read_reg1(rs1_sel),
    .read_reg2(rs2_sel),
    .reset(reset),
    .we(reg_we),
    .write_data(wr_data),
    .write_reg(rd_sel)
  );
  assign opcode = instr[15:12];
  assign rd_sel = instr[11:8];
  assign rs1_sel = instr[7:4];
  assign rs2_sel = _37_;
  assign imm = { instr[3], instr[3], instr[3], instr[3], instr[3], instr[3], instr[3], instr[3], instr[3], instr[3], instr[3], instr[3], instr[3:0] };
  assign alu_b_in = _38_;
  assign mem_addr = alu_result;
  assign mem_wdata = rd_data2;
  assign mem_we = mem_write;
  assign mem_re = mem_read;
  assign _06_ = _12_;
  assign _01_ = _08_;
  assign _02_ = _09_;
  assign _03_ = _10_;
  assign _05_ = _11_;
  assign _00_ = _07_;
  assign _04_ = _13_[15:0];
  assign _17_ = mem_read;
  assign _12_ = _16_;
  assign _07_ = _18_;
  assign _11_ = _22_;
  assign _08_ = _29_;
  assign _09_ = _33_;
  assign _10_ = _35_;
  assign wr_data = _16_;
  assign alu_ctrl = _18_;
  assign reg_we = _22_;
  assign mem_write = _35_;
  assign mem_read = _33_;
  assign alu_src_imm = _29_;
  assign _14_ = reset;
endmodule

(* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:1.1-38.10" *)
module regfile(clk, reset, we, read_reg1, read_reg2, write_reg, write_data, read_data1, read_data2);
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:4.11-4.13" *)
  input we;
  wire we;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:5.17-5.26" *)
  input [3:0] read_reg1;
  wire [3:0] read_reg1;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:6.17-6.26" *)
  input [3:0] read_reg2;
  wire [3:0] read_reg2;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:7.17-7.26" *)
  input [3:0] write_reg;
  wire [3:0] write_reg;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:8.18-8.28" *)
  input [15:0] write_data;
  wire [15:0] write_data;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:9.19-9.29" *)
  output [15:0] read_data1;
  wire [15:0] read_data1;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:10.19-10.29" *)
  output [15:0] read_data2;
  wire [15:0] read_data2;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *)
  wire [15:0] _000_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *)
  wire [15:0] _001_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [3:0] _002_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _003_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _004_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _005_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _006_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _007_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _008_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _009_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _010_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _011_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _012_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _013_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _014_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _015_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _016_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _017_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _018_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _019_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *)
  wire [15:0] _020_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *)
  wire [15:0] _021_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [3:0] _022_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _023_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [3:0] _024_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  wire [15:0] _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.26-36.43" *)
  wire _044_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.26-37.43" *)
  wire _045_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45" *)
  wire _046_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *)
  wire [3:0] _047_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *)
  wire [15:0] _048_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *)
  wire [3:0] _049_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *)
  wire [15:0] _050_;
  (* nosync = 32'd1 *)
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *)
  reg [3:0] _051_;
  (* nosync = 32'd1 *)
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *)
  reg [15:0] _052_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.28-31.45" *)
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire [3:0] _059_;
  wire _060_;
  wire [15:0] _061_;
  wire _062_;
  wire [15:0] _063_;
  wire _064_;
  wire [15:0] _065_;
  wire _066_;
  wire [15:0] _067_;
  wire _068_;
  wire [15:0] _069_;
  wire _070_;
  wire [15:0] _071_;
  wire _072_;
  wire [15:0] _073_;
  wire _074_;
  wire [15:0] _075_;
  wire _076_;
  wire [15:0] _077_;
  wire _078_;
  wire [15:0] _079_;
  wire _080_;
  wire [15:0] _081_;
  wire _082_;
  wire [15:0] _083_;
  wire _084_;
  wire [15:0] _085_;
  wire _086_;
  wire [15:0] _087_;
  wire _088_;
  wire [15:0] _089_;
  wire _090_;
  wire [15:0] _091_;
  wire _092_;
  wire [15:0] _093_;
  wire _094_;
  wire [15:0] _095_;
  wire _096_;
  wire [15:0] _097_;
  wire _098_;
  wire [15:0] _099_;
  wire _100_;
  wire [15:0] _101_;
  wire _102_;
  wire [15:0] _103_;
  wire _104_;
  wire [15:0] _105_;
  wire _106_;
  wire [15:0] _107_;
  wire _108_;
  wire [15:0] _109_;
  wire _110_;
  wire [15:0] _111_;
  wire _112_;
  wire [15:0] _113_;
  wire _114_;
  wire [15:0] _115_;
  wire _116_;
  wire [15:0] _117_;
  wire _118_;
  wire [15:0] _119_;
  wire _120_;
  wire [15:0] _121_;
  wire _122_;
  wire [15:0] _123_;
  wire _124_;
  wire [15:0] _125_;
  wire _126_;
  wire [15:0] _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire [15:0] _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.25-36.75" *)
  wire [15:0] _156_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.25-37.75" *)
  wire [15:0] _157_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[0] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[10] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[11] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[12] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[13] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[14] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[15] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[1] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[2] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[3] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[4] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[5] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[6] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[7] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[8] ;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:12.16-12.25" *)
  reg [15:0] \registers[9] ;
  assign _044_ = ! (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.26-36.43" *) read_reg1;
  assign _045_ = ! (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.26-37.43" *) read_reg2;
  assign _046_ = we && (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45" *) _053_;
  assign _053_ = | (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.28-31.45" *) write_reg;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _026_)
    if (_026_) \registers[0]  <= 16'h0000;
    else \registers[0]  <= _125_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _027_)
    if (_027_) \registers[1]  <= 16'h0000;
    else \registers[1]  <= _121_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _028_)
    if (_028_) \registers[2]  <= 16'h0000;
    else \registers[2]  <= _117_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _029_)
    if (_029_) \registers[3]  <= 16'h0000;
    else \registers[3]  <= _113_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _030_)
    if (_030_) \registers[4]  <= 16'h0000;
    else \registers[4]  <= _109_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _031_)
    if (_031_) \registers[5]  <= 16'h0000;
    else \registers[5]  <= _105_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _032_)
    if (_032_) \registers[6]  <= 16'h0000;
    else \registers[6]  <= _101_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _033_)
    if (_033_) \registers[7]  <= 16'h0000;
    else \registers[7]  <= _097_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _034_)
    if (_034_) \registers[8]  <= 16'h0000;
    else \registers[8]  <= _093_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _035_)
    if (_035_) \registers[9]  <= 16'h0000;
    else \registers[9]  <= _089_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _036_)
    if (_036_) \registers[10]  <= 16'h0000;
    else \registers[10]  <= _085_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _037_)
    if (_037_) \registers[11]  <= 16'h0000;
    else \registers[11]  <= _081_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _038_)
    if (_038_) \registers[12]  <= 16'h0000;
    else \registers[12]  <= _077_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _039_)
    if (_039_) \registers[13]  <= 16'h0000;
    else \registers[13]  <= _073_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _040_)
    if (_040_) \registers[14]  <= 16'h0000;
    else \registers[14]  <= _069_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _041_)
    if (_041_) \registers[15]  <= 16'h0000;
    else \registers[15]  <= _065_;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _042_)
    if (_042_) _051_ <= 4'hx;
    else _051_ <= 4'hx;
  (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:13.5-34.8" *)
  always @(posedge clk, posedge _043_)
    if (_043_) _052_ <= 16'hxxxx;
    else _052_ <= 16'hxxxx;
  assign _054_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'h4;
  assign _055_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'h3;
  assign _056_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'h2;
  assign _057_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'h1;
  assign _058_ = ! (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) _047_;
  assign _059_ = _060_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) write_reg : _051_;
  assign _061_ = _062_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) write_data : _052_;
  assign _063_ = _064_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[15] ;
  assign _064_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'hf;
  assign _065_ = _066_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _063_ : \registers[15] ;
  assign _067_ = _068_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[14] ;
  assign _068_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'he;
  assign _069_ = _070_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _067_ : \registers[14] ;
  assign _071_ = _072_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[13] ;
  assign _072_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'hd;
  assign _073_ = _074_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _071_ : \registers[13] ;
  assign _075_ = _076_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[12] ;
  assign _076_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'hc;
  assign _077_ = _078_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _075_ : \registers[12] ;
  assign _079_ = _080_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[11] ;
  assign _080_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'hb;
  assign _081_ = _082_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _079_ : \registers[11] ;
  assign _083_ = _084_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[10] ;
  assign _084_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'ha;
  assign _085_ = _086_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _083_ : \registers[10] ;
  assign _087_ = _088_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[9] ;
  assign _088_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'h9;
  assign _089_ = _090_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _087_ : \registers[9] ;
  assign _091_ = _092_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[8] ;
  assign _092_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'h8;
  assign _093_ = _094_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _091_ : \registers[8] ;
  assign _095_ = _096_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[7] ;
  assign _096_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'h7;
  assign _097_ = _098_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _095_ : \registers[7] ;
  assign _099_ = _100_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[6] ;
  assign _100_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'h6;
  assign _101_ = _102_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _099_ : \registers[6] ;
  assign _103_ = _104_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[5] ;
  assign _104_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'h5;
  assign _105_ = _106_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _103_ : \registers[5] ;
  assign _107_ = _108_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[4] ;
  assign _108_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'h4;
  assign _109_ = _110_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _107_ : \registers[4] ;
  assign _111_ = _112_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[3] ;
  assign _112_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'h3;
  assign _113_ = _114_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _111_ : \registers[3] ;
  assign _115_ = _116_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[2] ;
  assign _116_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'h2;
  assign _117_ = _118_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _115_ : \registers[2] ;
  assign _119_ = _120_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[1] ;
  assign _120_ = write_reg == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) 4'h1;
  assign _121_ = _122_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _119_ : \registers[1] ;
  assign _123_ = _124_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_data : \registers[0] ;
  assign _124_ = ! (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:32.13-32.47" *) write_reg;
  assign _125_ = _126_ ? (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.22-31.45|/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:31.18-33.12" *) _123_ : \registers[0] ;
  function [15:0] _235_;
    input [15:0] a;
    input [255:0] b;
    input [15:0] s;
    (* full_case = 32'd1 *)
    (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *)
    (* parallel_case *)
    casez (s)
      16'b???????????????1:
        _235_ = b[15:0];
      16'b??????????????1?:
        _235_ = b[31:16];
      16'b?????????????1??:
        _235_ = b[47:32];
      16'b????????????1???:
        _235_ = b[63:48];
      16'b???????????1????:
        _235_ = b[79:64];
      16'b??????????1?????:
        _235_ = b[95:80];
      16'b?????????1??????:
        _235_ = b[111:96];
      16'b????????1???????:
        _235_ = b[127:112];
      16'b???????1????????:
        _235_ = b[143:128];
      16'b??????1?????????:
        _235_ = b[159:144];
      16'b?????1??????????:
        _235_ = b[175:160];
      16'b????1???????????:
        _235_ = b[191:176];
      16'b???1????????????:
        _235_ = b[207:192];
      16'b??1?????????????:
        _235_ = b[223:208];
      16'b?1??????????????:
        _235_ = b[239:224];
      16'b1???????????????:
        _235_ = b[255:240];
      default:
        _235_ = a;
    endcase
  endfunction
  assign _127_ = _235_(16'hxxxx, { \registers[0] , \registers[1] , \registers[2] , \registers[3] , \registers[4] , \registers[5] , \registers[6] , \registers[7] , \registers[8] , \registers[9] , \registers[10] , \registers[11] , \registers[12] , \registers[13] , \registers[14] , \registers[15]  }, { _143_, _142_, _141_, _140_, _139_, _138_, _137_, _136_, _135_, _134_, _133_, _132_, _131_, _130_, _129_, _128_ });
  assign _128_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'hf;
  assign _129_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'he;
  assign _130_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'hd;
  assign _131_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'hc;
  assign _132_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'hb;
  assign _133_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'ha;
  assign _134_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'h9;
  assign _135_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'h8;
  assign _136_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'h7;
  assign _137_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'h6;
  assign _138_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'h5;
  assign _139_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'h4;
  assign _140_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'h3;
  assign _141_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'h2;
  assign _142_ = _049_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) 4'h1;
  assign _143_ = ! (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.55-37.64" *) _049_;
  function [15:0] _252_;
    input [15:0] a;
    input [255:0] b;
    input [15:0] s;
    (* full_case = 32'd1 *)
    (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *)
    (* parallel_case *)
    casez (s)
      16'b???????????????1:
        _252_ = b[15:0];
      16'b??????????????1?:
        _252_ = b[31:16];
      16'b?????????????1??:
        _252_ = b[47:32];
      16'b????????????1???:
        _252_ = b[63:48];
      16'b???????????1????:
        _252_ = b[79:64];
      16'b??????????1?????:
        _252_ = b[95:80];
      16'b?????????1??????:
        _252_ = b[111:96];
      16'b????????1???????:
        _252_ = b[127:112];
      16'b???????1????????:
        _252_ = b[143:128];
      16'b??????1?????????:
        _252_ = b[159:144];
      16'b?????1??????????:
        _252_ = b[175:160];
      16'b????1???????????:
        _252_ = b[191:176];
      16'b???1????????????:
        _252_ = b[207:192];
      16'b??1?????????????:
        _252_ = b[223:208];
      16'b?1??????????????:
        _252_ = b[239:224];
      16'b1???????????????:
        _252_ = b[255:240];
      default:
        _252_ = a;
    endcase
  endfunction
  assign _144_ = _252_(16'hxxxx, { \registers[0] , \registers[1] , \registers[2] , \registers[3] , \registers[4] , \registers[5] , \registers[6] , \registers[7] , \registers[8] , \registers[9] , \registers[10] , \registers[11] , \registers[12] , \registers[13] , \registers[14] , \registers[15]  }, { _058_, _057_, _056_, _055_, _054_, _155_, _154_, _153_, _152_, _151_, _150_, _149_, _148_, _147_, _146_, _145_ });
  assign _145_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'hf;
  assign _146_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'he;
  assign _147_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'hd;
  assign _148_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'hc;
  assign _149_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'hb;
  assign _150_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'ha;
  assign _151_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'h9;
  assign _152_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'h8;
  assign _153_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'h7;
  assign _154_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'h6;
  assign _155_ = _047_ == (* full_case = 32'd1 *) (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.55-36.64" *) 4'h5;
  assign _156_ = _044_ ? (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:36.25-36.75" *) 16'h0000 : _048_;
  assign _157_ = _045_ ? (* src = "/home/vlsilab/rtl2gdsagi/processor_16b/regfile.v:37.25-37.75" *) 16'h0000 : _050_;
  assign read_data1 = _156_;
  assign read_data2 = _157_;
  assign _047_ = read_reg1;
  assign _049_ = read_reg2;
  assign _001_ = _021_;
  assign _000_ = _020_;
  assign _003_ = _023_;
  assign _002_ = _022_;
  assign _021_ = _127_;
  assign _020_ = _144_;
  assign _060_ = _046_;
  assign _024_ = _059_;
  assign _062_ = _046_;
  assign _025_ = _061_;
  assign _023_ = _025_;
  assign _022_ = _024_;
  assign _066_ = _046_;
  assign _010_ = _065_;
  assign _070_ = _046_;
  assign _009_ = _069_;
  assign _074_ = _046_;
  assign _008_ = _073_;
  assign _078_ = _046_;
  assign _007_ = _077_;
  assign _082_ = _046_;
  assign _006_ = _081_;
  assign _086_ = _046_;
  assign _005_ = _085_;
  assign _090_ = _046_;
  assign _019_ = _089_;
  assign _094_ = _046_;
  assign _018_ = _093_;
  assign _098_ = _046_;
  assign _017_ = _097_;
  assign _102_ = _046_;
  assign _016_ = _101_;
  assign _106_ = _046_;
  assign _015_ = _105_;
  assign _110_ = _046_;
  assign _014_ = _109_;
  assign _114_ = _046_;
  assign _013_ = _113_;
  assign _118_ = _046_;
  assign _012_ = _117_;
  assign _122_ = _046_;
  assign _011_ = _121_;
  assign _126_ = _046_;
  assign _004_ = _125_;
  assign _050_ = _127_;
  assign _048_ = _144_;
  assign _043_ = reset;
  assign _042_ = reset;
  assign _041_ = reset;
  assign _040_ = reset;
  assign _039_ = reset;
  assign _038_ = reset;
  assign _037_ = reset;
  assign _036_ = reset;
  assign _035_ = reset;
  assign _034_ = reset;
  assign _033_ = reset;
  assign _032_ = reset;
  assign _031_ = reset;
  assign _030_ = reset;
  assign _029_ = reset;
  assign _028_ = reset;
  assign _027_ = reset;
  assign _026_ = reset;
endmodule
