"""Renderer tests.

The load-bearing property is byte-identity: the same IR must always produce the
same script. Without it, "diff attempt 3 against attempt 4" is meaningless and
controlled A/B comparison (review 12) cannot work.

The second property is that the renderer is the *only* thing that writes tool
syntax, so these tests also check that generated scripts never contain a
construct that would weaken a check.
"""

from __future__ import annotations

import pytest

from rtl2gdsagi.ir import IR
from rtl2gdsagi.render import RenderContext, render
from rtl2gdsagi.stages import StageId

RENDERABLE = [
    StageId.SDC, StageId.SYNTHESIS, StageId.LEC_SYNTH,
    StageId.STA_PRE, StageId.STA_POSTCTS, StageId.STA_SIGNOFF,
    StageId.FLOORPLAN, StageId.PDN, StageId.PLACEMENT, StageId.CTS,
    StageId.ROUTING, StageId.EXTRACTION, StageId.ANTENNA, StageId.GDSOUT,
]


@pytest.fixture
def ctx(fake_pdk, tmp_path) -> RenderContext:
    work = tmp_path / "work"
    work.mkdir()
    keys = [
        "netlist", "sdc", "floorplan_def", "pdn_def", "placement_def",
        "cts_def", "routed_def", "routed_netlist", "spef", "final_gds",
    ]
    inputs = {}
    for k in keys:
        p = work / f"{k}.dat"
        p.write_text(f"# {k}\n", encoding="utf-8")
        inputs[k] = p
    outputs = {k: work / f"out_{k}" for k in keys + [
        "synth_json", "placed_netlist", "cts_netlist", "congestion_report",
        "route_drc", "antenna_report", "drc_report", "lvs_report",
    ]}
    return RenderContext(
        top="widget", pdk=fake_pdk, work_dir=work,
        inputs=inputs, outputs=outputs,
        facts={
            "sources": [str(work / "widget.v")],
            "clocks": [{"name": "i_clk", "period_ns": 10.0}],
            "inputs": ["i_clk", "i_rst_n", "i_data"],
            "outputs": ["o_data"],
            "cell_gds": [str(fake_pdk.cell_gds()[0])] if fake_pdk.cell_gds() else [],
            "site": "unithd",
        },
    )


@pytest.mark.parametrize("stage", RENDERABLE, ids=lambda s: s.value)
def test_rendering_is_byte_identical(stage, ctx):
    """Same IR in, same bytes out. This is what makes diffs meaningful."""
    ir = IR()
    a = render(stage, ir, ctx)
    b = render(stage, IR(), ctx)
    assert a == b
    assert a.startswith("# generated by rtl2gdsagi")


@pytest.mark.parametrize("stage", RENDERABLE, ids=lambda s: s.value)
def test_rendered_scripts_contain_no_timestamp(stage, ctx):
    """A clock reading in the output would destroy byte-identity."""
    import re
    text = render(stage, IR(), ctx)
    assert not re.search(r"\b(20\d\d-\d\d-\d\d|\d\d:\d\d:\d\d)\b", text)


def test_changing_a_knob_changes_the_script(ctx):
    ir = IR()
    before = render(StageId.FLOORPLAN, ir, ctx)
    ir.update("floorplan", {"core_utilization": 0.70})
    after = render(StageId.FLOORPLAN, ir, ctx)
    assert before != after
    assert "70.00" in after


def test_sdc_constrains_every_clock_domain(ctx):
    """A missing create_clock silently produces falsely clean timing."""
    ctx.facts["clocks"] = [
        {"name": "i_clk", "period_ns": 10.0},
        {"name": "i_pclk", "period_ns": 40.0},
        {"name": "w_clk25m", "period_ns": 40.0},
    ]
    text = render(StageId.SDC, IR(), ctx)
    assert text.count("create_clock") == 3
    for clk in ("i_clk", "i_pclk", "w_clk25m"):
        assert f"-name {clk} " in text


def test_sdc_does_not_use_remove_from_collection(ctx):
    """OpenSTA has no such command; it errored the whole constraint file."""
    text = render(StageId.SDC, IR(), ctx)
    assert "remove_from_collection" not in text


def test_sdc_excludes_clock_ports_from_input_delay(ctx):
    text = render(StageId.SDC, IR(), ctx)
    line = next(l for l in text.splitlines() if "set_input_delay" in l)
    assert "i_data" in line and "i_rst_n" in line
    assert "i_clk" not in line.split("[get_ports")[1]


def test_sdc_with_no_clock_emits_a_virtual_clock(ctx):
    ctx.facts["clocks"] = []
    text = render(StageId.SDC, IR(), ctx)
    assert "create_clock -name vclk" in text


def test_def_reading_stages_do_not_link_design(ctx):
    """link_design after read_def fails with STA-0008; the DEF is the design."""
    for stage in (StageId.PDN, StageId.PLACEMENT, StageId.CTS,
                  StageId.ROUTING, StageId.EXTRACTION, StageId.ANTENNA):
        text = render(stage, IR(), ctx)
        assert "read_def" in text, stage
        assert "link_design" not in text, f"{stage} still calls link_design"


def test_floorplan_reads_verilog_and_links(ctx):
    """Floorplan is the one stage that legitimately links a netlist."""
    text = render(StageId.FLOORPLAN, IR(), ctx)
    assert "read_verilog" in text and "link_design widget" in text


def test_cts_always_supplies_a_buffer_list(ctx):
    """CTS-0055: OpenROAD refuses to run without -buf_list."""
    text = render(StageId.CTS, IR(), ctx)
    assert "-buf_list" in text
    assert "-root_buf" in text


def test_routing_rejects_an_inverted_layer_range(ctx):
    ir = IR()
    ir.update("routing", {"min_layer": 5, "max_layer": 2})
    with pytest.raises(ValueError, match="min_layer"):
        render(StageId.ROUTING, ir, ctx)


def test_detailed_route_is_bounded_to_the_same_layers_as_global_route(ctx):
    """set_routing_layers binds the global router only. Without explicit
    bounds the detailed router uses the whole stack, drops onto li1, and
    lands wires 0.145um from the cells' li1 power rails -- li.3 spacing
    violations that detailed_route itself reports as clean."""
    ir = IR()
    ir.update("routing", {"min_layer": 2, "max_layer": 4})
    text = render(StageId.ROUTING, ir, ctx)
    assert "set_routing_layers -signal met2-met4" in text
    droute = next(l for l in text.splitlines() if l.startswith("detailed_route"))
    assert "-bottom_routing_layer met2" in droute
    assert "-top_routing_layer met4" in droute


def test_signoff_scripts_never_suppress_checks(ctx):
    """No rendered script may contain a waiver construct."""
    banned = ("waive", "skip_rule", "ignore_error", "-force_pass",
              "set_dont_check", "suppress")
    for stage in RENDERABLE:
        text = render(stage, IR(), ctx).lower()
        for token in banned:
            assert token not in text, f"{stage} emitted {token!r}"


def test_gdsout_merges_cell_gds_before_reading_the_def(ctx):
    """Order matters: the DEF's instance references must resolve against real
    geometry, not against LEF abstracts."""
    text = render(StageId.GDSOUT, IR(), ctx)
    assert text.index("ly.read(gds)") < text.index("lefdef_config")


def test_gdsout_fails_on_a_missing_or_empty_top_cell(ctx):
    text = render(StageId.GDSOUT, IR(), ctx)
    assert "top is None" in text and "sys.exit(2)" in text
    assert "top.is_empty()" in text and "sys.exit(4)" in text


def test_gdsout_script_is_valid_python(ctx):
    import ast
    ast.parse(render(StageId.GDSOUT, IR(), ctx))


def test_unresolved_reference_check_lives_on_the_written_gds(ctx):
    """The authoritative pre-merge test reads the artifact that goes to
    signoff, not the in-memory layout -- see tests/test_gds_premerge.py."""
    from rtl2gdsagi.checks.gds import read_gds
    assert callable(read_gds)


def test_signoff_sta_reads_parasitics_and_pre_layout_does_not(ctx):
    """The only thing distinguishing the three STA runs is what they read."""
    pre = render(StageId.STA_PRE, IR(), ctx)
    signoff = render(StageId.STA_SIGNOFF, IR(), ctx)
    assert "read_spef" not in pre
    assert "read_spef" in signoff


def test_all_sta_stages_emit_parseable_slack_markers(ctx):
    """result_check greps these; losing them would break the verdict silently."""
    for stage in (StageId.STA_PRE, StageId.STA_POSTCTS, StageId.STA_SIGNOFF):
        text = render(stage, IR(), ctx)
        for marker in ("setup_wns", "hold_wns", "setup_tns", "hold_tns"):
            assert marker in text, f"{stage} lost {marker}"


def test_synthesis_maps_to_the_pdk_liberty(ctx, fake_pdk):
    text = render(StageId.SYNTHESIS, IR(), ctx)
    assert str(fake_pdk.liberty_path) in text
    assert "abc -liberty" in text
    assert "write_verilog" in text


def test_antenna_repair_sits_between_global_and_detailed_route(ctx):
    """Ordering regression.

    `repair_antennas` creates diode wires using live global-routing state.
    Placed after `detailed_route` that state is gone and OpenROAD aborts with
    GRT-0221 ("Cannot create wire for net ..."), after having already spent the
    full detailed-routing runtime.
    """
    text = render(StageId.ROUTING, IR(), ctx)
    g = text.index("global_route")
    r = text.index("repair_antennas")
    d = text.index("detailed_route")
    assert g < r < d, "repair_antennas must run between global and detailed route"


def test_antenna_repair_names_a_diode_cell_from_the_pdk(ctx):
    text = render(StageId.ROUTING, IR(), ctx)
    line = next(l for l in text.splitlines() if "repair_antennas" in l)
    assert "diode" in line


def test_diode_insertion_can_be_disabled_without_touching_the_check(ctx):
    """Turning off repair must not turn off the antenna *gate*."""
    ir = IR()
    ir.update("routing", {"insert_diodes": False})
    text = render(StageId.ROUTING, ir, ctx)
    assert "repair_antennas" not in text
    # The antenna stage is a separate hard gate and is unaffected.
    from rtl2gdsagi.stages import Gate, get_stage
    assert get_stage(StageId.ANTENNA).gate is Gate.HARD


def test_gdsout_uses_the_real_klayout_lefdef_api(ctx):
    """`LoadLayoutOptions.set_option_by_name` does not exist in KLayout 0.28+.

    `lefdef_config` is a live property, and the wrong call aborts the
    stream-out with AttributeError after the merge has already been read.
    """
    text = render(StageId.GDSOUT, IR(), ctx)
    assert "set_option_by_name" not in text
    assert "opt.lefdef_config" in text
    assert "cfg.lef_files" in text


def test_floorplan_inserts_well_taps(ctx):
    """An untied nwell is a real latchup risk; the process requires taps.

    Recorded honestly: adding taps did not reduce the nwell.*/hvtp. violation
    count on the real OV7670 run (440 -> 601, scaling with cell count). Those
    are width/spacing rules on abutting cell geometry. Taps stay because the
    process demands them, not as a DRC fix.
    """
    text = render(StageId.FLOORPLAN, IR(), ctx)
    assert "tapcell" in text
    assert "-tapcell_master" in text
    assert "-distance" in text


def test_floorplan_still_writes_its_def(ctx):
    """Guard against an edit dropping the handover artifact."""
    text = render(StageId.FLOORPLAN, IR(), ctx)
    assert "write_def" in text
    assert text.index("tapcell") < text.index("write_def")


def test_tap_spacing_is_schema_bounded(ctx):
    from rtl2gdsagi.ir import SchemaViolation
    ir = IR()
    ir.update("floorplan", {"tapcell_distance_um": 20.0})
    assert "-distance 20.000" in render(StageId.FLOORPLAN, ir, ctx)
    with pytest.raises(SchemaViolation):
        ir.update("floorplan", {"tapcell_distance_um": 500.0})


def test_filler_is_inserted_after_every_cell_is_placed(ctx):
    """Row gaps must be filled, but only once nothing more will be placed.

    Without filler the nwell is a row of islands instead of one continuous
    strip, and signoff DRC reports nwell/hvtp width and spacing violations at
    every gap — on a layout that is otherwise perfectly legal.

    Doing it at placement time is worse than not doing it: the clock-tree
    buffers then have nowhere to go and CTS dies with DPL-0036 naming a FILLER
    instance. So it belongs at the end of routing, after CTS and antenna repair.
    """
    assert "filler_placement" not in render(StageId.PLACEMENT, IR(), ctx)

    text = render(StageId.ROUTING, IR(), ctx)
    assert "filler_placement" in text
    assert text.index("detailed_route") < text.index("filler_placement")
    assert text.index("filler_placement") < text.index("write_def")


def test_filler_cells_come_from_the_pdk(ctx):
    fillers = ctx.pdk.filler_cells()
    assert fillers, "no filler cells discovered in the LEF"
    line = next(l for l in render(StageId.ROUTING, IR(), ctx).splitlines()
                if "filler_placement" in l)
    assert fillers[0] in line


def test_gdsout_prunes_cells_the_design_does_not_use(ctx):
    """The final GDS must have exactly one top cell.

    The whole standard-cell library is merged in so the DEF's instance
    references resolve; that leaves hundreds of unused cells behind, and every
    one of them is a top cell. LVS then refuses the layout outright — its
    runset has no way to say which top cell is the design ("The layout has
    multiple top cells"). Pruning also shrinks the file enormously.
    """
    text = render(StageId.GDSOUT, IR(), ctx)
    assert "called_cells" in text
    assert "delete_cell" in text
    # Prune after the merge and before the write, or it achieves nothing.
    assert text.index("ly.read(gds)") < text.index("called_cells")
    assert text.index("called_cells") < text.index("ly.write")


def test_gdsout_uses_the_pdk_layer_map(ctx):
    """Without it, DEF geometry is streamed to invented layer numbers.

    The consequence is not a crash but a false clean: the DRC deck inspects
    real layer numbers, finds no routing there, and reports zero violations on
    a layout it never examined.
    """
    text = render(StageId.GDSOUT, IR(), ctx)
    assert "cfg.map_file" in text
    assert str(ctx.pdk.layer_map_path) in text
    # Set before the DEF is read, or it has no effect.
    assert text.index("cfg.map_file") < text.index("lefdef_config") or \
           text.index("cfg.map_file") < text.index("opt)")


def test_pdn_ties_the_grid_down_to_the_cell_rails(ctx):
    """A power grid that only connects to itself powers nothing.

    Connecting met4-met5 alone leaves the straps floating above the design:
    the standard cells receive no power, the GDS ends up with a single via,
    and LVS reports "must-connect subnets of VGND must be connected further up
    in the hierarchy". The layout looks plausible and routes cleanly.
    """
    text = render(StageId.PDN, IR(), ctx)
    assert "-followpins" in text, "the cell rails are never drawn"
    connects = [l for l in text.splitlines() if "add_pdn_connect" in l]
    assert any("met1" in l for l in connects), "grid never reaches the cell rails"
    assert any("met4" in l and "met5" in l for l in connects)


def test_pdn_draws_rails_before_connecting_them(ctx):
    text = render(StageId.PDN, IR(), ctx)
    assert text.index("-followpins") < text.index("add_pdn_connect")


def test_signoff_sta_refuses_to_run_without_parasitics(ctx):
    """Signoff timing without a SPEF is not signoff timing.

    Quietly skipping read_spef would leave the authoritative check running on
    estimates while still calling itself authoritative -- the same shape as
    every other silent-degradation bug in this flow.
    """
    ctx.inputs.pop("spef", None)
    with pytest.raises(ValueError, match="SPEF"):
        render(StageId.STA_SIGNOFF, IR(), ctx)


def test_post_cts_sta_does_not_need_a_spef(ctx):
    """It is a hold check with a real clock tree, not a parasitic check."""
    ctx.inputs.pop("spef", None)
    text = render(StageId.STA_POSTCTS, IR(), ctx)
    assert "read_spef" not in text
    assert "read_def" in text


def test_synthesis_gives_abc_the_real_clock_period(ctx):
    """Yosys does not read SDC.

    The target period reaches synthesis only through abc's -D flag, in
    picoseconds. The old value was a literal `-D 1` — one picosecond — so the
    DELAY strategies were optimising against an impossible target, which abc
    treats as no constraint at all. Synthesis was never timing-driven.
    """
    ir = IR()
    ir.update("synthesis", {"strategy": "DELAY0"})
    ctx.facts["clocks"] = [{"name": "i_clk", "period_ns": 10.0}]
    line = next(l for l in render(StageId.SYNTHESIS, ir, ctx).splitlines()
                if l.startswith("abc "))
    assert "-D 10000" in line          # 10 ns expressed in ps


def test_area_strategies_also_get_the_timing_target(ctx):
    """An area-first mapping still has to respect the clock."""
    ir = IR()
    ir.update("synthesis", {"strategy": "AREA0"})
    ctx.facts["clocks"] = [{"name": "i_clk", "period_ns": 10.0}]
    line = next(l for l in render(StageId.SYNTHESIS, ir, ctx).splitlines()
                if l.startswith("abc "))
    assert "-D 10000" in line


def test_a_design_with_no_clock_passes_no_target(ctx):
    ir = IR()
    ctx.facts["clocks"] = []
    line = next(l for l in render(StageId.SYNTHESIS, ir, ctx).splitlines()
                if l.startswith("abc "))
    assert "-D" not in line


def test_the_tightest_clock_sets_the_synthesis_target(ctx):
    """A multi-clock design must be synthesised for its fastest domain."""
    ir = IR()
    ir.update("synthesis", {"strategy": "DELAY0"})
    ctx.facts["clocks"] = [
        {"name": "slow", "period_ns": 40.0},
        {"name": "fast", "period_ns": 8.0},
    ]
    line = next(l for l in render(StageId.SYNTHESIS, ir, ctx).splitlines()
                if l.startswith("abc "))
    assert "-D 8000" in line


def test_cts_repairs_hold_after_the_clock_tree_exists(ctx):
    """Hold is fixed by adding delay on short paths, and nowhere else.

    It belongs after clock_tree_synthesis because hold is dominated by clock
    skew, which is not a physical thing until the tree exists. Without this
    step the flow has no mechanism to fix hold at all -- it can only report the
    violation and stop.
    """
    text = render(StageId.CTS, IR(), ctx)
    assert "repair_timing -hold" in text
    assert text.index("clock_tree_synthesis") < text.index("repair_timing -hold")
    # Legalise afterwards: the repair inserts cells.
    assert text.index("repair_timing -hold") < text.index("detailed_placement")


def test_hold_margin_is_schema_bounded(ctx):
    from rtl2gdsagi.ir import SchemaViolation
    ir = IR()
    ir.update("cts", {"hold_margin_ns": 0.2})
    assert "-hold_margin 0.2000" in render(StageId.CTS, ir, ctx)
    with pytest.raises(SchemaViolation):
        ir.update("cts", {"hold_margin_ns": 5.0})


def test_disabling_hold_repair_does_not_disable_the_hold_check(ctx):
    """Turning off the repair must not turn off the gate that catches it."""
    from rtl2gdsagi.stages import Gate, get_stage
    ir = IR()
    ir.update("cts", {"fix_hold": False})
    assert "repair_timing -hold" not in render(StageId.CTS, ir, ctx)
    assert get_stage(StageId.STA_POSTCTS).gate is Gate.HARD
    assert get_stage(StageId.STA_SIGNOFF).gate is Gate.HARD


def test_hold_is_repaired_with_routed_parasitics_not_just_estimates(ctx):
    """Post-CTS repair alone cannot see the violation.

    With placement estimates OpenROAD reports "No hold violations found" and
    hold reads +0.058 ns; real interconnect turns it to -0.124 ns at signoff.
    The repair has to run where the parasitics are close to final, and before
    a detailed route that can wire in whatever cells it inserts.
    """
    text = render(StageId.ROUTING, IR(), ctx)
    assert "repair_timing -hold" in text
    assert "estimate_parasitics -global_routing" in text
    assert text.index("global_route") < text.index("repair_timing -hold")
    assert text.index("repair_timing -hold") < text.index("detailed_route")


def test_disabling_hold_repair_removes_it_from_routing_too(ctx):
    ir = IR()
    ir.update("cts", {"fix_hold": False})
    assert "repair_timing -hold" not in render(StageId.ROUTING, ir, ctx)


def test_placement_padding_is_set_before_placement(ctx):
    """Padding reserves space; setting it afterwards reclaims nothing.

    Cells packed edge to edge leave the router no room to land the via pads it
    needs to reach their pins, which surfaces as li1 spacing violations at
    signoff rather than as an honest routing failure.
    """
    ir = IR()
    ir.update("placement", {"padding_sites": 2})
    text = render(StageId.PLACEMENT, ir, ctx)
    assert "set_placement_padding -global -left 2 -right 2" in text
    assert text.index("set_placement_padding") < text.index("global_placement")
