"""Deterministic IR -> tool-syntax rendering.

The agent never writes a line of TCL. It writes schema-bounded IR values
(:mod:`rtl2gdsagi.ir`) and this module renders them, so the same IR always
produces byte-identical scripts. That reproducibility is what makes rollback
diffs and controlled A/B comparison meaningful (review 7, 10, 12).

Renderers are pure functions of (IR section, RenderContext). Nothing here reads
the clock or the environment, because a timestamp in a rendered script would
destroy the byte-identity property.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

from .checks.tools import (
    ANTENNA_COMPLETE_MARKER,
    SPEF_ANNOTATED_MARKER,
    SPEF_COVERAGE_MARKER,
)
from .ir import IR
from .pdk import PDKConfig
from .stages import StageId

BANNER = "# generated by rtl2gdsagi from schema-validated IR -- do not hand-edit"


@dataclass
class RenderContext:
    """Everything a renderer may reference besides the IR itself."""

    top: str
    pdk: PDKConfig
    work_dir: Path
    #: Artifact key -> path, supplied by the orchestrator from the ledger.
    inputs: dict[str, Path] = field(default_factory=dict)
    outputs: dict[str, Path] = field(default_factory=dict)
    #: Deterministic facts from the characterize stage.
    facts: dict[str, Any] = field(default_factory=dict)

    def inp(self, key: str) -> str:
        try:
            return str(self.inputs[key])
        except KeyError:
            raise KeyError(f"renderer needs input artifact {key!r}") from None

    def out(self, key: str) -> str:
        try:
            return str(self.outputs[key])
        except KeyError:
            raise KeyError(f"renderer needs output path {key!r}") from None


def _hdr(what: str) -> list[str]:
    return [BANNER, f"# stage: {what}", ""]


# ---------------------------------------------------------------- SDC ------

def render_sdc(ir: IR, ctx: RenderContext) -> str:
    """Generate the SDC. The user never hand-writes constraints (review 4.1)."""
    s = ir.section("sdc")
    period = float(s["default_clock_period_ns"])
    clocks = ctx.facts.get("clocks") or []
    lines = _hdr("sdc")
    lines.append("set_units -time ns -capacitance pF")
    lines.append("")

    if not clocks:
        # Characterization found no clock port; emit a virtual clock so STA has
        # something to reason about rather than silently constraining nothing.
        lines.append(f"create_clock -name vclk -period {period:.4f}")
        lines.append("")
    for clk in clocks:
        name = clk["name"] if isinstance(clk, dict) else str(clk)
        p = float(clk.get("period_ns", period)) if isinstance(clk, dict) else period
        lines.append(f"create_clock -name {name} -period {p:.4f} [get_ports {{{name}}}]")

    unc = float(s["clock_uncertainty_ns"])
    if unc > 0:
        lines.append(f"set_clock_uncertainty {unc:.4f} [all_clocks]")
    lines.append("")

    ind = period * float(s["input_delay_frac"])
    outd = period * float(s["output_delay_frac"])
    # Ordered, so the reference clock is a decision rather than an accident.
    #
    # This used to pick `next(iter(clock_names))` out of a *set*. Python
    # randomises string hashing per process, so on a multi-clock design the
    # clock every set_input_delay/set_output_delay referenced changed between
    # runs of the identical design -- three different answers in six processes
    # when measured. Identical inputs must render identical SDC, or timing
    # results are not comparable across runs and no A/B experiment means
    # anything.
    #
    # Picking the first declared clock is still a guess, and a poor one on a
    # genuinely multi-clock design -- see the SDC limitation in the README --
    # but it is at least a reproducible guess.
    ordered_clocks = [
        (c["name"] if isinstance(c, dict) else str(c)) for c in clocks
    ]
    clock_names = set(ordered_clocks)
    data_inputs = [p for p in ctx.facts.get("inputs", []) if p not in clock_names]
    ref_clock = ordered_clocks[0] if ordered_clocks else "vclk"

    if data_inputs:
        lines.append(
            f"set_input_delay {ind:.4f} -clock {ref_clock} "
            f"[get_ports {{{' '.join(data_inputs)}}}]"
        )
    if ctx.facts.get("outputs"):
        lines.append(
            f"set_output_delay {outd:.4f} -clock {ref_clock} [all_outputs]"
        )
        lines.append(f"set_load {float(s['output_load_pf']):.4f} [all_outputs]")
    lines.append("")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------ synthesis ----

def render_synthesis(ir: IR, ctx: RenderContext) -> str:
    s = ir.section("synthesis")
    lines = _hdr("synthesis (yosys)")
    for src in ctx.facts.get("sources", []):
        lines.append(f"read_verilog -sv {src}")
    lines.append("")
    lines.append(f"hierarchy -check -top {ctx.top}")
    lines += ["", "proc", "opt -full"]
    if s["share_resources"]:
        lines.append("share")
    lines += ["fsm", "opt -full", "memory", "opt -full"]
    if s["flatten"]:
        lines.append("flatten")
    lines.append("opt -full")
    lines.append("")
    if s["adder_type"] != "yosys":
        lines.append(f"techmap -map +/adff2dff.v  ;# adder_type={s['adder_type']}")
    lines.append("techmap")
    lines.append("opt -fast")
    lines.append("")
    lib = str(ctx.pdk.liberty_path)
    if s["dff_map"]:
        lines.append(f"dfflibmap -liberty {lib}")
    strategy = str(s["strategy"])
    # Give abc the real target period. Yosys does not read SDC, so this is the
    # only route by which synthesis learns how fast the design must run --
    # without it the DELAY strategies optimise against nothing. `-D 1` (one
    # picosecond) was doing exactly that: asking for the impossible, which abc
    # treats as no useful constraint at all.
    clocks = ctx.facts.get("clocks") or []
    periods = [
        float(c.get("period_ns", 0.0)) if isinstance(c, dict) else 0.0
        for c in clocks
    ]
    period_ns = min((p for p in periods if p > 0), default=0.0)
    # Every strategy gets the target, not just the DELAY ones: an area-first
    # mapping still has to respect the clock, it just does not chase margin
    # beyond it.
    abc_flag = f"-D {period_ns * 1000:.0f}" if period_ns > 0 else ""
    lines.append(f"abc -liberty {lib} {abc_flag}".rstrip())
    lines += [
        "setundef -zero",
        "splitnets",
        "opt_clean -purge",
        "",
        f"hilomap -hicell sky130_fd_sc_hd__conb_1 HI -locell sky130_fd_sc_hd__conb_1 LO"
        if ctx.pdk.name.startswith("sky130") else "",
        "",
        "check",
        "stat -liberty " + lib,
        f"write_verilog -noattr -noexpr -nohex -nodec {ctx.out('netlist')}",
        f"write_json {ctx.out('synth_json')}",
        "",
    ]
    return "\n".join(x for x in lines if x is not None) + "\n"


# ------------------------------------------------------------------ LEC ----

def formal_pdk_proc() -> Path:
    """Path to the vendored SkyWater formal-model preprocessor."""
    return Path(__file__).resolve().parent / "resources" / "formal_pdk_proc.py"


def render_lec(ir: IR, ctx: RenderContext) -> str:
    """Emit an EQY config for RTL-versus-netlist equivalence (review 4.4).

    This is an ``.eqy`` file, not a Yosys script. Yosys' built-in ``equiv_*``
    flow cannot do this job on a real standard-cell library: reading the liberty
    as ``-lib`` makes every cell a blackbox, so there is no function to compare
    and the proof stalls with unproven points on a design that is fine.

    The PDK's behavioural models would supply that function, but they use
    Verilog UDPs (``primitive ... endprimitive``) which Yosys cannot parse.
    ``formal_pdk_proc.py`` rewrites them into formal-friendly Verilog, which is
    what makes the whole thing work -- the same approach EQY's own SKY130
    example uses.
    """
    s = ir.section("lec")
    stage_dir = ctx.work_dir
    formal_v = stage_dir / "formal_pdk.v"
    models = " ".join(str(p) for p in ctx.pdk.formal_cell_models())

    netlist_key = "routed_netlist" if "routed_netlist" in ctx.inputs else "netlist"
    sources = " ".join(str(p) for p in ctx.facts.get("sources", []))

    lines = [
        "# generated by rtl2gdsagi from schema-validated IR -- do not hand-edit",
        f"# stage: formal equivalence ({netlist_key} vs RTL)",
        "",
        # No [options] section: EQY accepts only splitnets/insbuf there, and
        # proof depth belongs to the strategy below.
        "[gold]",
        f"read_verilog -formal -sv {sources}",
        "",
        "[gate]",
    ]
    if models:
        lines.append(
            f"exec -- python3 {formal_pdk_proc()} {models} -o {formal_v}"
        )
        lines.append(f"read -sv {formal_v} {ctx.inp(netlist_key)}")
    else:
        lines.append(f"read -sv {ctx.inp(netlist_key)}")
    lines += [
        "",
        "[script]",
        f"hierarchy -check -top {ctx.top}",
        "prep",
        "async2sync",
        # Lower memories to flops+logic. The SAT strategy cannot reason about
        # $mem cells ("No configured strategy supports partition ... as it
        # contains memory"), and the alternative needs an SMT solver. This runs
        # in the *shared* script section, so gold and gate are transformed
        # identically and the comparison stays honest.
        "memory_map",
        # Strip power-on state from BOTH sides before comparing.
        #
        # The netlist is written with `write_verilog -noattr`, which drops the
        # `init` attributes that the RTL side still carries. That asymmetry is
        # not a design difference, but a solver sees the two sides disagreeing
        # at time 0 and reports "partitions not equivalent" -- telling someone
        # their working counter is broken. Unsetting init on both sides asks
        # the right question: is the *logic* equivalent, from any state.
        "setattr -unset init",
        "opt -full",
        "",
        # Two strategies, tried in order. `sat` is fast and settles most
        # partitions; deep sequential logic comes back "equivalence unknown"
        # from it no matter how far the depth is raised (verified: depth 40
        # changed nothing but the runtime). Those need an SMT engine, which is
        # what the second strategy provides when sby and a solver are present.
        "[strategy sat]",
        "use sat",
        f"depth {int(s['induction_steps'])}",
        "",
    ]
    if s["smt_solver"]:
        lines += [
            "[strategy smt]",
            "use sby",
            f"depth {int(s['induction_steps'])}",
            f"engine smtbmc {s['smt_solver']}",
            "",
        ]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ STA ----

def render_sta(ir: IR, ctx: RenderContext, *, stage: StageId) -> str:
    """One renderer for all three STA invocations.

    OpenSTA does not know whether it is "pre-layout" or "signoff"; that is
    determined entirely by what parasitics it is given (review 15). So the only
    difference between these scripts is the SPEF and the reports requested.
    """
    s = ir.section("sta")
    lines = _hdr(f"STA ({stage.value})")

    # Pre-layout STA runs in standalone OpenSTA against the netlist. The
    # post-CTS and signoff runs must run inside OpenROAD instead: standalone
    # OpenSTA has no read_def or read_spef, so it cannot see the clock tree or
    # the extracted parasitics that make those checks authoritative.
    in_openroad = stage in (StageId.STA_POSTCTS, StageId.STA_SIGNOFF)

    if in_openroad:
        lines += [f"read_lef {ctx.pdk.tech_lef_path}", f"read_lef {ctx.pdk.cell_lef_path}"]

    for corner in s["corners"]:
        libp = ctx.pdk.liberty_for_corner(str(corner))
        lines.append(f"read_liberty {libp}")
    lines.append("")

    if stage is StageId.STA_POSTCTS:
        lines.append(f"read_def {ctx.inp('cts_def')}")
    elif stage is StageId.STA_SIGNOFF:
        lines.append(f"read_def {ctx.inp('routed_def')}")
        # Signoff timing without extracted parasitics is not signoff timing.
        # Silently omitting this would leave the authoritative check running on
        # estimates while still calling itself authoritative -- so a missing
        # SPEF is an error, not a degraded mode.
        if "spef" not in ctx.inputs:
            raise ValueError(
                "sta_signoff has no SPEF: signoff timing must use extracted "
                "parasitics, and running it without them would report a result "
                "it has not earned"
            )
        # A successful read_spef prints nothing at all, so the log of a run
        # that annotated parasitics is indistinguishable from one that did not
        # -- and a *failed* parse is only a warning, after which the analysis
        # continues with no interconnect and reports plausible numbers. This
        # marker is the positive evidence: it can only appear if read_spef
        # returned without aborting the script, and check_sta additionally
        # refuses any SPEF parse warning.
        lines.append(f"read_spef {ctx.inp('spef')}")
        lines.append(f'puts "{SPEF_ANNOTATED_MARKER} {ctx.inp("spef")}"')
        # The marker above only proves the script got past read_spef. It is
        # equally present when the SPEF annotated nothing -- which is how a
        # forged SPEF earned an authoritative PASS (P0-R1). This asks the
        # timing engine itself how much of the design it actually annotated;
        # `check_sta` requires the answer to be "all of it".
        lines.append(f'puts "{SPEF_COVERAGE_MARKER}"')
        lines.append("report_parasitic_annotation")
    else:
        lines.append(f"read_verilog {ctx.inp('netlist')}")
        lines.append(f"link_design {ctx.top}")
    lines.append("")

    lines.append(f"read_sdc {ctx.inp('sdc')}")
    if in_openroad:
        lines.append("set_propagated_clock [all_clocks]")
    lines.append("")

    if float(s["derate_setup"]) > 0:
        lines.append(f"set_timing_derate -late {1.0 + float(s['derate_setup']):.4f}")
    if float(s["derate_hold"]) > 0:
        lines.append(f"set_timing_derate -early {1.0 - float(s['derate_hold']):.4f}")
    lines.append("")

    n = int(s["max_paths"])
    lines += [
        "puts \"=== check_setup ===\"",
        "check_setup -verbose",
        "",
        "puts \"=== setup ===\"",
        f"report_checks -path_delay max -group_count {n} -digits 4",
        "puts \"=== hold ===\"",
        f"report_checks -path_delay min -group_count {n} -digits 4",
        "",
        "puts \"=== wns/tns ===\"",
        "puts \"setup_wns [sta::worst_slack -max]\"",
        "puts \"setup_tns [sta::total_negative_slack -max]\"",
        "puts \"hold_wns [sta::worst_slack -min]\"",
        "puts \"hold_tns [sta::total_negative_slack -min]\"",
        "",
        "exit 0",
        "",
    ]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------- OpenROAD ----

def _openroad_preamble(ctx: RenderContext, *, liberty: bool = False) -> list[str]:
    lines = [f"read_lef {ctx.pdk.tech_lef_path}", f"read_lef {ctx.pdk.cell_lef_path}"]
    for extra in ctx.facts.get("macro_lefs", []):
        lines.append(f"read_lef {extra}")
    if liberty:
        lines.append(f"read_liberty {ctx.pdk.liberty_path}")
    return lines


def _read_db(ctx: RenderContext, key: str) -> list[str]:
    """Load a DEF handed over by the previous stage.

    Deliberately no `link_design`: that command links a Verilog netlist into a
    design, and calling it after read_def fails with STA-0008 because the DEF
    already *is* the linked design.
    """
    return [f"read_def {ctx.inp(key)}"]


def render_floorplan(ir: IR, ctx: RenderContext) -> str:
    s = ir.section("floorplan")
    lines = _hdr("floorplan (openroad)") + _openroad_preamble(ctx)
    lines += [
        f"read_verilog {ctx.inp('netlist')}",
        f"link_design {ctx.top}",
        f"read_sdc {ctx.inp('sdc')}",
        "",
        f"initialize_floorplan -utilization {float(s['core_utilization']) * 100:.2f}"
        f" -aspect_ratio {float(s['aspect_ratio']):.4f}"
        f" -core_space {float(s['core_margin_um']):.3f}"
        f" -site {ctx.facts.get('site', 'unithd')}",
        "",
        "make_tracks",
        f"place_pins -hor_layers {ctx.facts.get('pin_hor_layer', 'met3')}"
        f" -ver_layers {ctx.facts.get('pin_ver_layer', 'met2')}",
        "",
        "remove_buffers",
        "",
    ]

    # Well taps. Required by the process: an untied nwell is a real latchup
    # risk, and no SKY130 tapeout ships without them.
    #
    # Note for anyone reading the DRC numbers: inserting taps did *not* reduce
    # the nwell.*/hvtp.* violation count on this design -- it rose from 440 to
    # 601, scaling with cell count. Those violations are width/spacing rules on
    # abutting cell geometry, i.e. a stream-out merge question, not a missing
    # tie-down. Taps are kept because the process requires them, not because
    # they fix that count.
    taps = ctx.pdk.tap_cells()
    if taps:
        lines += [
            f"tapcell -distance {float(s['tapcell_distance_um']):.3f}"
            f" -tapcell_master {taps[0]}",
            "",
        ]

    lines += [
        f"write_def {ctx.out('floorplan_def')}",
        "report_design_area",
        "exit 0",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_pdn(ir: IR, ctx: RenderContext) -> str:
    s = ir.section("pdn")
    lines = _hdr("pdn (openroad)") + _openroad_preamble(ctx)
    lines += [
        *_read_db(ctx, "floorplan_def"),
        "",
        "add_global_connection -net VPWR -pin_pattern {^VPWR$} -power",
        "add_global_connection -net VGND -pin_pattern {^VGND$} -ground",
        "global_connect",
        "set_voltage_domain -power VPWR -ground VGND",
        "",
        "define_pdn_grid -name stdcell -voltage_domains CORE",
    ]
    if s["core_ring"]:
        lines.append(
            "add_pdn_ring -grid stdcell -layers {met4 met5}"
            f" -widths {{{float(s['strap_width_um']):.3f} {float(s['strap_width_um']):.3f}}}"
            " -spacings {1.7 1.7} -core_offsets {4.5 4.5}"
        )
    lines += [
        # The standard-cell rails themselves. -followpins traces the VPWR/VGND
        # pins the cells already have, turning abutting cell rails into
        # continuous met1 stripes.
        "add_pdn_stripe -grid stdcell -layer met1 -width 0.48 -followpins",
        "",
        f"add_pdn_stripe -grid stdcell -layer met4 -width {float(s['strap_width_um']):.3f}"
        f" -pitch {float(s['strap_pitch_um']):.3f}"
        f" -offset {float(s['strap_offset_um']):.3f} -extend_to_core_ring",
        f"add_pdn_stripe -grid stdcell -layer met5 -width {float(s['strap_width_um']):.3f}"
        f" -pitch {float(s['strap_pitch_um']):.3f}"
        f" -offset {float(s['strap_offset_um']):.3f} -extend_to_core_ring",
        # Tie the straps down to the cell rails. Connecting only met4-met5
        # leaves the whole grid floating above the design: the cells get no
        # power at all, and LVS says so with "must-connect subnets of VGND
        # must be connected further up in the hierarchy".
        "add_pdn_connect -grid stdcell -layers {met1 met4}",
        "add_pdn_connect -grid stdcell -layers {met4 met5}",
        "",
        "pdngen",
        "",
        f"write_def {ctx.out('pdn_def')}",
        "exit 0",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_placement(ir: IR, ctx: RenderContext) -> str:
    s = ir.section("placement")
    lines = _hdr("placement (openroad)") + _openroad_preamble(ctx, liberty=True)
    lines += [
        *_read_db(ctx, "pdn_def"),
        f"read_sdc {ctx.inp('sdc')}",
        "",
        # Padding must be set before placement, not after: it reserves the
        # space rather than reclaiming it.
        f"set_placement_padding -global -left {int(s['padding_sites'])}"
        f" -right {int(s['padding_sites'])}",
        "",
        f"global_placement -density {float(s['target_density']):.4f}"
        + (" -routability_driven" if s["routability_driven"] else ""),
        "",
        "estimate_parasitics -placement",
        "repair_design",
        "",
        "detailed_placement",
        "check_placement -verbose",
        "",
    ]

    lines += [
        "puts \"=== congestion ===\"",
        f"global_route -congestion_report_file {ctx.out('congestion_report')}"
        " -allow_congestion",
        "",
        f"write_def {ctx.out('placement_def')}",
        f"write_verilog {ctx.out('placed_netlist')}",
        "exit 0",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_cts(ir: IR, ctx: RenderContext) -> str:
    s = ir.section("cts")
    lines = _hdr("cts (openroad)") + _openroad_preamble(ctx, liberty=True)
    lines += [
        *_read_db(ctx, "placement_def"),
        f"read_sdc {ctx.inp('sdc')}",
        "",
        "set_wire_rc -clock -layer met5",
    ]
    # -buf_list is mandatory (CTS-0055), so it is always emitted. An explicit
    # root_buffer from the IR overrides the PDK-derived list.
    root = str(s["root_buffer"]).strip()
    buffers = [root] if root else ctx.pdk.clock_buffers()
    if not buffers:
        raise ValueError(
            f"no clock buffer cells found in {ctx.pdk.cell_lef_path}; set "
            "cts.root_buffer explicitly"
        )
    cts_cmd = (
        "clock_tree_synthesis -sink_clustering_enable"
        f" -buf_list {{{' '.join(buffers)}}}"
        f" -root_buf {buffers[0]}"
    )
    lines += [
        cts_cmd,
        "",
        "set_propagated_clock [all_clocks]",
        "estimate_parasitics -placement",
        "repair_clock_nets",
        "",
    ]

    # Hold repair: insert delay cells on short paths.
    #
    # This is the only legitimate way to fix hold. It belongs here rather than
    # earlier because hold is dominated by clock skew, which does not exist as
    # a physical thing until the clock tree does -- and it must never be
    # "fixed" by editing RTL or by relaxing the constraint, which is why the
    # taxonomy routes a hold failure to this stage and forbids both.
    if s["fix_hold"]:
        # -allow_setup_violations lets the repair spend setup margin to buy
        # hold margin. That trade is only safe because signoff STA checks both
        # afterwards: if it goes too far, the setup check fails and the flow
        # stops. The gate is what makes the trade safe, not the flag.
        lines += [
            f"repair_timing -hold -hold_margin {float(s['hold_margin_ns']):.4f}"
            " -allow_setup_violations",
            "",
        ]

    lines += [
        "detailed_placement",
        "",
        "puts \"=== cts report ===\"",
        "report_clock_skew",
        "report_cts",
        "",
        f"write_def {ctx.out('cts_def')}",
        f"write_verilog {ctx.out('cts_netlist')}",
        "exit 0",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_routing(ir: IR, ctx: RenderContext) -> str:
    s = ir.section("routing")
    lo, hi = int(s["min_layer"]), int(s["max_layer"])
    if lo > hi:
        raise ValueError(f"routing.min_layer ({lo}) exceeds max_layer ({hi})")
    lines = _hdr("routing (openroad)") + _openroad_preamble(ctx, liberty=True)
    lines += [
        *_read_db(ctx, "cts_def"),
        f"read_sdc {ctx.inp('sdc')}",
        "",
        "set_propagated_clock [all_clocks]",
        # The clock range must stay inside the signal range.
        #
        # This used to be `met{max(lo, 3)}-met{hi}`, which for any schema-legal
        # max_layer below 3 emits a range whose minimum exceeds its maximum --
        # `met3-met2` -- and OpenROAD rejects it outright with GRT-0056 before
        # routing anything. `max_layer` is agent-writable over 1..12, so the
        # renderer was capable of turning a legal IR into an illegal tool
        # argument. Clamping the clock floor to `hi` is correct independently of
        # any benchmark: a renderer must emit a legal command for every input
        # the schema admits.
        f"set_routing_layers -signal met{lo}-met{hi} "
        f"-clock met{min(max(lo, 3), hi)}-met{hi}",
        "global_route",
        "",
    ]

    # Hold repair, using global-route parasitics.
    #
    # Doing this after CTS is not enough: with placement estimates hold looks
    # positive (+0.058 ns on the OV7670 test design, and OpenROAD reports "No
    # hold violations found"), while real interconnect turns it negative
    # (-0.124 ns at signoff). Global-route parasitics are close enough to final
    # to expose it, and there is still a detailed_route afterwards to wire up
    # whatever cells the repair inserts.
    cts_cfg = ir.section("cts")
    if cts_cfg["fix_hold"]:
        lines += [
            "estimate_parasitics -global_routing",
            f"repair_timing -hold -hold_margin {float(cts_cfg['hold_margin_ns']):.4f}"
            " -allow_setup_violations",
            "detailed_placement",
            "global_route",
            "",
        ]
    if s["insert_diodes"]:
        # Diode insertion must sit between global and detailed route: it needs
        # live global-routing state to create the diode wires, and running it
        # after detailed_route fails with GRT-0221 because that state is gone.
        # This repairs antenna violations; the antenna *check* is still its own
        # hard gate afterwards, so this cannot suppress a real violation.
        diodes = ctx.pdk.antenna_diodes()
        lines.append(
            f"repair_antennas {diodes[0]}" if diodes else "repair_antennas"
        )
        lines.append("")
    # The layer bounds have to be repeated here. set_routing_layers binds the
    # *global* router only; without these two flags the detailed router falls
    # back to the whole stack and routes on li1, which the global route never
    # planned for. On the OV7670 test design that produced a 20um vertical li1
    # wire in the margin left of the rows, 0.145um from the leftmost cells'
    # li1 power rails -- an li.3 spacing violation (rule 0.17um) on every row
    # it passed. detailed_route itself reported "0 violations" throughout,
    # because it is not checking li1 against cell rails it believes are out of
    # scope; only the signoff deck saw them.
    lines += [
        f"detailed_route -output_drc {ctx.out('route_drc')}"
        f" -bottom_routing_layer met{lo} -top_routing_layer met{hi}"
        f" -droute_end_iter {int(s['droute_iters'])} -verbose 1",
        "",
    ]

    # Fill the gaps between cells -- last, once nothing more will be placed.
    #
    # Without filler the nwell is a row of islands rather than one continuous
    # strip, and signoff DRC reports nwell/hvtp width and spacing violations at
    # every gap, on a layout that is otherwise perfectly legal.
    #
    # It must come after CTS and antenna repair, not after placement: filling
    # the gaps earlier leaves the clock-tree buffers nowhere to go, and detailed
    # placement dies with DPL-0036 naming a FILLER instance.
    fillers = ctx.pdk.filler_cells() if s["insert_filler"] else []
    if fillers:
        lines += [f"filler_placement {{{' '.join(fillers)}}}", "check_placement", ""]

    lines += [
        f"write_def {ctx.out('routed_def')}",
        f"write_verilog {ctx.out('routed_netlist')}",
        "exit 0",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_extraction(ir: IR, ctx: RenderContext) -> str:
    s = ir.section("extraction")
    corner = str(s["corner"])
    rules = ctx.pdk.openrcx_rules(corner)
    lines = _hdr("parasitic extraction (openroad)") + _openroad_preamble(ctx)
    lines += [
        *_read_db(ctx, "routed_def"),
        "",
        f"define_process_corner -ext_model_index 0 {corner}",
        f"extract_parasitics -ext_model_file {rules} -corner_cnt 1",
        f"write_spef {ctx.out('spef')}",
        "exit 0",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_antenna(ir: IR, ctx: RenderContext) -> str:
    lines = _hdr("antenna check (openroad)") + _openroad_preamble(ctx)
    lines += [
        *_read_db(ctx, "routed_def"),
        "",
        # `check_antennas` writes nothing to its report file when the design is
        # clean, and an empty file is not evidence -- the artifact ledger skips
        # zero-length outputs, so the antenna gate reached signoff with nothing
        # bound to it and signoff refused the candidate. Record the check's own
        # return value (the violation count) so a clean result is still a
        # positive statement that the check ran and what it found.
        f"set _ant_violations [check_antennas "
        f"-report_file {ctx.out('antenna_report')} -verbose]",
        f"set _ant_fh [open {ctx.out('antenna_report')} a]",
        f'puts $_ant_fh "{ANTENNA_COMPLETE_MARKER} violations=$_ant_violations"',
        "close $_ant_fh",
        "exit 0",
        "",
    ]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------- KLayout -----

def render_gdsout(ir: IR, ctx: RenderContext) -> str:
    """Stream out exactly one merged GDS.

    Written as a KLayout Python script rather than TCL because KLayout's Python
    API is what actually exposes the merge, and because it lets the script fail
    loudly on an unresolved cell reference instead of silently writing a GDS
    with empty proxies -- which is precisely how a pre-merge artifact ends up
    passing DRC.
    """
    s = ir.section("gdsout")
    lines = [
        BANNER,
        "# stage: gdsout (klayout)",
        "import pya, sys",
        "",
        "ly = pya.Layout()",
        "opt = pya.LoadLayoutOptions()",
        "",
        "# Merge every standard-cell / macro GDS *before* the DEF, so the DEF's",
        "# instance references resolve against real geometry rather than proxies.",
        "for gds in [",
    ]
    for g in ctx.facts.get("cell_gds", []):
        lines.append(f"    {str(g)!r},")
    lines += [
        "]:",
        "    ly.read(gds)",
        "",
        "# lefdef_config is a live property on LoadLayoutOptions; the",
        "# generic option-setter used by older examples does not exist here.",
        "cfg = opt.lefdef_config",
        f"cfg.lef_files = {[str(ctx.pdk.tech_lef_path), str(ctx.pdk.cell_lef_path)]!r}",
        "cfg.read_lef_with_def = False",
        "# The layer map is not optional.",
        "#",
        "# Without it KLayout assigns sequential layer numbers to everything it",
        "# reads from the DEF -- routing landed on 3/0, 5/0, 7/0 instead of",
        "# SKY130's li1 67/20, met1 68/20, met2 69/20. The geometry is all",
        "# there and looks fine in a viewer, but the DRC deck inspects the real",
        "# layer numbers and therefore never sees the routing at all: it checks",
        "# only the standard cells, whose geometry came from the cell GDS with",
        "# correct layers, and reports a clean result on an unchecked layout.",
        "# It is also why LVS extracted a top cell with almost no pins.",
        f"cfg.map_file = {str(ctx.pdk.layer_map_path)!r}",
        "cfg.produce_pin_names = True",
        f"ly.read({ctx.inp('routed_def')!r}, opt)",
        "",
        f"top = ly.cell({ctx.top!r})",
        "if top is None:",
        f"    sys.stderr.write('gdsout: top cell {ctx.top} not found after merge\\n')",
        "    sys.exit(2)",
        "",
        "# Keep only what the design actually uses.",
        "#",
        "# The whole standard-cell library was merged in so the DEF's instance",
        "# references would resolve, which leaves hundreds of unused cells behind.",
        "# Every one of them is a top cell, and a GDS with multiple top cells",
        "# cannot be handed to LVS: the runset has no way to say which one is the",
        "# design ('The layout has multiple top cells'). Pruning also shrinks the",
        "# file by orders of magnitude.",
        "keep = set(top.called_cells())",
        "keep.add(top.cell_index())",
        "doomed = [c.cell_index() for c in ly.each_cell()",
        "          if c.cell_index() not in keep]",
        "for ci in doomed:",
        "    ly.delete_cell(ci)",
        "sys.stderr.write('gdsout: pruned %d unused cell(s), %d remain\\n'",
        "                 % (len(doomed), ly.cells()))",
        "",
        "# Report cells that are placed but carry no geometry. This is advisory",
        "# here: the authoritative unresolved-reference check runs against the",
        "# written GDS itself (rtl2gdsagi.checks.gds), which is the artifact that",
        "# actually goes to signoff. Failing in-script on every empty library",
        "# cell would reject perfectly good stream-outs.",
        "placed = set()",
        "for c in ly.each_cell():",
        "    for inst in c.each_inst():",
        "        placed.add(inst.cell.name)",
        "hollow = sorted(n for n in placed if ly.cell(n) and ly.cell(n).is_empty())",
        "if hollow:",
        "    sys.stderr.write('gdsout: %d placed cell(s) have no geometry: %s\\n'",
        "                     % (len(hollow), hollow[:20]))",
        "",
        "if top.is_empty():",
        f"    sys.stderr.write('gdsout: top cell {ctx.top} is empty\\n')",
        "    sys.exit(4)",
        "",
    ]
    if s["merge_mode"] == "flatten_top":
        lines.append("top.flatten(-1, True)")
    lines += [
        f"ly.write({ctx.out('final_gds')!r})",
        f"sys.stderr.write('gdsout: wrote %s cells to {ctx.out('final_gds')}\\n' % ly.cells())",
        "",
    ]
    return "\n".join(lines) + "\n"


RENDERERS: dict[StageId, Callable[[IR, RenderContext], str]] = {
    StageId.SDC: render_sdc,
    StageId.SYNTHESIS: render_synthesis,
    StageId.LEC_SYNTH: render_lec,
    StageId.LEC_ROUTE: render_lec,
    StageId.FLOORPLAN: render_floorplan,
    StageId.PDN: render_pdn,
    StageId.PLACEMENT: render_placement,
    StageId.CTS: render_cts,
    StageId.ROUTING: render_routing,
    StageId.EXTRACTION: render_extraction,
    StageId.ANTENNA: render_antenna,
    StageId.GDSOUT: render_gdsout,
}


def render(stage: StageId, ir: IR, ctx: RenderContext) -> str:
    """Render the script for ``stage``. Raises KeyError if it has no renderer."""
    if stage in (StageId.STA_PRE, StageId.STA_POSTCTS, StageId.STA_SIGNOFF):
        return render_sta(ir, ctx, stage=stage)
    try:
        fn = RENDERERS[stage]
    except KeyError:
        raise KeyError(f"stage {stage.value!r} has no renderer") from None
    return fn(ir, ctx)
