"""Run state: a single ``run_state.json``, atomically rewritten.

Written after every state transition with tmp-file + fsync + ``os.replace``, so
the file on disk is always a complete, parseable snapshot even if the process is
killed mid-write. That property is what makes ``--resume-from`` trustworthy.
"""

from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

from .artifacts import ArtifactLedger
from .stages import STAGE_ORDER, StageId

STATE_FILENAME = "run_state.json"
STATE_VERSION = 2


class StageStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    OK = "ok"
    FAILED = "failed"
    #: Skipped because --resume-from started after it, or a prior run passed it.
    SKIPPED = "skipped"

    def __str__(self) -> str:
        return self.value


class RunStatus(str, Enum):
    RUNNING = "running"
    OK = "ok"
    FAILED = "failed"

    def __str__(self) -> str:
        return self.value


@dataclass
class StageState:
    status: StageStatus = StageStatus.PENDING
    #: Total times the tool was invoked for this stage (1 + fix attempts).
    attempts: int = 0
    #: Times a config artifact was generated or regenerated by the API.
    configs_generated: int = 0
    #: Claude API calls made on behalf of this stage.
    api_calls: int = 0
    retry_limit: int = 0
    #: Kind of the last verdict this stage produced ("pass",
    #: "qor_below_target", "fail"). Status alone cannot tell "passed" apart
    #: from "completed but proved nothing": a testbench that runs without
    #: printing a result leaves the stage OK while verifying nothing, and
    #: certification has to be able to distinguish those.
    last_verdict: str = ""
    last_error: str = ""
    #: Verbatim tail of the failing tool output, for the failure report.
    last_detail: str = ""
    started_at: float | None = None
    ended_at: float | None = None
    #: Per-attempt breadcrumbs: what happened, in order.
    history: list[dict[str, Any]] = field(default_factory=list)

    @property
    def duration_s(self) -> float | None:
        if self.started_at is None or self.ended_at is None:
            return None
        return self.ended_at - self.started_at

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status.value,
            "attempts": self.attempts,
            "configs_generated": self.configs_generated,
            "api_calls": self.api_calls,
            "retry_limit": self.retry_limit,
            "last_verdict": self.last_verdict,
            "last_error": self.last_error,
            "last_detail": self.last_detail,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "duration_s": self.duration_s,
            "history": self.history,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "StageState":
        return cls(
            status=StageStatus(d.get("status", "pending")),
            attempts=int(d.get("attempts", 0)),
            configs_generated=int(d.get("configs_generated", 0)),
            api_calls=int(d.get("api_calls", 0)),
            retry_limit=int(d.get("retry_limit", 0)),
            last_verdict=d.get("last_verdict", ""),
            last_error=d.get("last_error", ""),
            last_detail=d.get("last_detail", ""),
            started_at=d.get("started_at"),
            ended_at=d.get("ended_at"),
            history=list(d.get("history") or []),
        )


@dataclass
class RunState:
    run_id: str
    run_dir: Path
    config: dict[str, Any] = field(default_factory=dict)
    status: RunStatus = RunStatus.RUNNING
    started_at: float = field(default_factory=time.time)
    ended_at: float | None = None
    stages: dict[StageId, StageState] = field(default_factory=dict)
    artifacts: ArtifactLedger = field(default_factory=ArtifactLedger)
    version: int = STATE_VERSION

    def __post_init__(self) -> None:
        self.run_dir = Path(self.run_dir)
        for sid in STAGE_ORDER:
            self.stages.setdefault(sid, StageState())

    # ---- accessors -------------------------------------------------------

    @property
    def path(self) -> Path:
        return self.run_dir / STATE_FILENAME

    def stage(self, sid: StageId | str) -> StageState:
        return self.stages[StageId(sid) if not isinstance(sid, StageId) else sid]

    def completed_stages(self) -> list[StageId]:
        return [s for s in STAGE_ORDER if self.stages[s].status is StageStatus.OK]

    def first_incomplete(self) -> StageId | None:
        for s in STAGE_ORDER:
            if self.stages[s].status is not StageStatus.OK:
                return s
        return None

    def failed_stage(self) -> StageId | None:
        for s in STAGE_ORDER:
            if self.stages[s].status is StageStatus.FAILED:
                return s
        return None

    # ---- persistence -----------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": self.version,
            "run_id": self.run_id,
            "run_dir": str(self.run_dir),
            "status": self.status.value,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "config": self.config,
            "stages": {s.value: self.stages[s].to_dict() for s in STAGE_ORDER},
            "artifacts": self.artifacts.to_dict(),
        }

    def save(self) -> Path:
        """Atomically rewrite run_state.json. Safe to call on every transition."""
        self.run_dir.mkdir(parents=True, exist_ok=True)
        target = self.path
        tmp = target.with_suffix(".json.tmp")
        payload = json.dumps(self.to_dict(), indent=2, sort_keys=False)
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(payload)
            fh.write("\n")
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, target)
        # fsync the directory so the rename itself is durable.
        try:
            dfd = os.open(self.run_dir, os.O_RDONLY)
            try:
                os.fsync(dfd)
            finally:
                os.close(dfd)
        except OSError:  # pragma: no cover - not fatal, e.g. exotic filesystems
            pass
        return target

    @classmethod
    def load(cls, path: str | os.PathLike[str]) -> "RunState":
        """Load a state file, or the run directory containing one."""
        p = Path(path).expanduser()
        if p.is_dir():
            p = p / STATE_FILENAME
        data = json.loads(p.read_text(encoding="utf-8"))
        version = int(data.get("version", 0))
        if version > STATE_VERSION:
            raise ValueError(
                f"{p} was written by a newer rtl2gdsagi (state version {version} > "
                f"{STATE_VERSION}); upgrade rather than resuming with this build"
            )
        st = cls(
            run_id=data["run_id"],
            run_dir=Path(data.get("run_dir", p.parent)),
            config=data.get("config") or {},
            status=RunStatus(data.get("status", "running")),
            started_at=float(data.get("started_at") or time.time()),
            ended_at=data.get("ended_at"),
            artifacts=ArtifactLedger.from_dict(data.get("artifacts")),
            version=version or STATE_VERSION,
        )
        for name, raw in (data.get("stages") or {}).items():
            try:
                sid = StageId(name)
            except ValueError:
                continue  # stage removed in a later version; ignore
            st.stages[sid] = StageState.from_dict(raw)
        return st


def new_run_id(now: float | None = None) -> str:
    """UTC timestamp run id, sorts chronologically and is filesystem-safe."""
    t = time.gmtime(now if now is not None else time.time())
    return time.strftime("%Y-%m-%dT%H-%M-%SZ", t)
